import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  inro_container: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  inro_container1: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  inro_container2: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    paddingLeft: 10,
    paddingRight: 10,
    alignItems: "center",
  },
  img_intro: {
    width: 250,
    height: 300,
  },
  txt_1: {
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
  },
  txt_4: {
    color: "white",
    fontSize: 20,
    letterSpacing: 2,
  },

  btn_2: {
    backgroundColor: "#2b80ff",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 120,
    borderRadius: 20,
    height: 40,
  },
  box: {
    width: 100,
    height: 100,
    backgroundColor: "blue",
  },
  dot_view: {
    display: "flex",
    flexDirection: "row",
    width: 25,
    justifyContent: "space-between",
  },
  dot1: {
    backgroundColor: "black",
    width: 5,
    height: 5,
    borderRadius: 50,
  },
  dot2: {
    backgroundColor: "#b5b5b5",
    width: 5,
    height: 5,
    borderRadius: 50,
  },
  txt_2: {
    textAlign: "center",
    paddingLeft: 20,
    paddingRight: 20,
    color: "#747474",
  },
  txt_3: {
    color: "#747474",
    fontSize: 20,
    letterSpacing: 2,
  },
  btn_1: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 120,
    borderRadius: 20,
    height: 40,
  },
  login_img: {
    width: 250,
    height: 300,
  },
  login_1: {
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "left",
    width: "110%",
    letterSpacing: 2,
  },
  icon: {
    width: 20,
    height: 20,
  },
  field_back: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    width:"100%",
  },
  btn_login: {
    backgroundColor: "#2b80ff",
    height: 40,
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  login_btn_back:{
    height: 40,
    width: "110%",
  },
  login_2: {
    fontSize: 20,
    letterSpacing: 2,
    fontWeight: "bold",
    color: "white",
  },
  feild_1: {
    fontSize: 20,
    letterSpacing: 2,
    width:"70%",
    borderBottomWidth: 1,
    borderColor: "#a3a3a3",
  },
  login_container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 45,
    gap: 15,
  },
  login_img1: {
    width: 35,
    height: 35,
  },
  login_txt1: {
    fontSize: 15,
    color: "#a3a3a3",
    fontWeight: "bold",
    letterSpacing: 2,
  },
  login_com1: {
    display: "flex",
    flexDirection: "row",
    justifyContent:"center",
    alignItems: "center",
    gap: 20,
  },
  login_com2: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    gap: 10,
  },
  login_txt2: {
    fontSize: 20,
    fontWeight: "bold",
    letterSpacing: 2,
  },
  login_txt3: {
    fontSize: 14,
    color: "#a3a3a3",
  },
  login_txt4: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#2b80ff",
    letterSpacing:2
  },
  sign_1: {
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "left",
    letterSpacing: 2,
    marginBottom:20
  },
  btn_sign: {
    backgroundColor: "#2b80ff",
    height: 40,
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  feildr_1: {
    fontSize: 20,
    letterSpacing: 2,
    width: "70%",
    borderBottomWidth: 1,
    borderColor: "#a3a3a3",
  },
  sign_container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  sign_txt1: {
    fontSize: 15,
    color: "#a3a3a3",
    fontWeight: "bold",
    letterSpacing: 2,
    textAlign:"center"
  },
  sign_com1: {
    display: "flex",
    flexDirection: "row",
    justifyContent:"center",
    gap:20,
    alignItems: "center"
  },
  sign_com2: {
    display: "flex",
    flexDirection: "row",
    justifyContent:"center",
    gap:5,
    alignItems: "center",
  },
  reg_scroll: {
    flex: 1,
    justifyContent: "space-evenly",
    paddingLeft:20,
    paddingRight:20,
    flexDirection:"column",
    paddingBottom:"60%",
    gap:20
  },
  error_message:{
    color: "red",
    fontWeight: "bold",
    backgroundColor: "#ff9c9c",
    padding: 5,
    borderRadius: 2,
    width:"100%"
  },
  home_container: {
    flex: 1,
    alignItems: "flex-start",
    paddingLeft: 20,
  },
  home_img1: {
    width: 25,
    height: 25,
  },
  home_img2: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
  },
  home_img3: {
    width: 100,
    height: 100,
    overflow: "hidden",
    borderRadius: 10,
  },
  home_img4: { width: 15, height: 15 },
  home_header: {
    height: "20%",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "space-around",
    paddingRight: 20,
  },
  home_body: {
    height: "55%",
    width: "100%",
  },
  home_scroll_sub_view: {
    display: "flex",
    flexDirection: "row",
    gap: 20,
    paddingRight: 20,
  },
  home_txt_1: {
    fontSize: 40,
    color: "#8e8e8e",
    letterSpacing: 2,
    fontWeight: "bold",
  },
  home_txt_2: {
    fontSize: 20,
    letterSpacing: 2,
  },
  home_txt_3: {
    fontSize: 20,
    color: "white",
    letterSpacing: 2,
    fontWeight: "bold",
    display: "flex",
    alignItems: "flex-start",
    paddingLeft: 10,
  },
  home_txt_4: {
    fontSize: 12,
    color: "white",
    letterSpacing: 2,
    display: "flex",
    alignItems: "flex-start",
    paddingLeft: 10,
    paddingBottom: 10,
  },
  home_txt_5: {
    fontSize: 25,
    color: "black",
    fontWeight: "bold",
    letterSpacing: 2,
  },
  home_txt_6: {
    fontSize: 15,
    letterSpacing: 2,
    color: "white",
    fontWeight: "bold",
  },
  home_txt_7: {
    fontSize: 20,
    fontWeight: "bold",
    letterSpacing: 2,
  },
  home_txt_8: {
    fontSize: 15,
    letterSpacing: 2,
    color: "#8e8e8e",
    fontWeight: "bold",
  },
  home_con1: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    width: "100%",
  },
  home_con2: {
    width: 250,
    height: 150,
    overflow: "hidden",
    borderRadius: 10,
  },
  home_con3: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    height: "20%",
    width: "100%",
  },
  home_con4: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    paddingRight: 20,
  },
  home_con5: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    gap: 15,
    paddingTop: 20,
    paddingBottom: 50,
  },
  home_con6: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 20,
    width: 220,
  },
  home_con7: {
    width: 100,
    height: 100,
    overflow: "hidden",
    borderRadius: 10,
  },
  home_con8: {
    display: "flex",
    flexDirection: "row",
    gap: 20,
    justifyContent: "flex-start",
  },
  home_con9: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
  },
  home_btn_category: {
    backgroundColor: "#2b80ff",
    width: 100,
    height: 30,
    borderRadius: 5,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  readscreen_con1: {
    width: "100%",
    height: 350,
    display: "flex",
    justifyContent: "flex-start",
  },
  readscreen_img1: { width: "100%", height: 250 },
  readscreen_con2: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-end",
    padding: 20,
    gap: 20,
  },
  readscreen_con3: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: 100,
    paddingLeft: 10,
    paddingRight: 10,
  },
  readscreen_img2: { width: 20, height: 20 },
  readscreen_txt1: {
    textAlign: "left",
    fontSize: 35,
    letterSpacing: 2,
    fontWeight: "bold",
  },
  readscreen_txt2: {
    textAlign: "center",
    fontWeight: "bold",
    letterSpacing: 2,
  },
  readscreen_txt3: {
    paddingLeft: 10,
    paddingRight: 10,
    textAlign: "left",
    paddingBottom: 400,
    paddingTop: 10,
    fontSize: 17,
    color: "#888888",
  },
  readscreen_txt4:{
    textAlign: "left",
    fontSize: 15,
    letterSpacing: 2,
    color: "#fe165c",
    fontWeight: "bold",
  },
  readscreen_btn1: {
    width: "30%",
    height: 40,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    // borderWidth: 2,
    borderColor: "black",
  },
});
